import definitions.ActivityInitiator;
import definitions.kYouActivities;
import definitions.Moods;

import java.sql.Timestamp;

/**
 * Created by itaimendelsohn on 11/26/15.
 * represents the basic evetn for an activity ML class. shall be extended per activity type using inheritance (later..)
 */

public class MLEvent {
    // the ID of kYou user
    int personID;

    // event time stamp - dd-hh-mm . seconds and below is not in use
    int dayNum;
    int hour;
    int minute;

    // event type for kYou initiated events
    kYouActivities kYouActivityType = kYouActivities.NONE;

    // meta-data - for now an int, later will be extended
    int metaData;

    boolean accepted;

    // states (might change per activity type) and are generated by query the raw (simEvent) data
    Moods moodState; // the avg mood of the elder in the last hour (?) TODO: define the way we calculate it
    boolean wasActiveState; // true if did any activity in the last hour(?)
    boolean ateState; //true if ate "lately" (last hour?)
    boolean spokeState; // true if spoke with someone in the last hour (?)
    // TODO add more states


    public MLEvent(int personID, int dayNum, int hour, int minute, kYouActivities kYouActivityType, int metaData,boolean accepted) {
        this.personID = personID;
        this.dayNum = dayNum;
        this.hour = hour;
        this.minute = minute;
        this.kYouActivityType = kYouActivityType;
        this.metaData = metaData;
        this.accepted = accepted;
    }

    public void setMoodState(Moods moodState) {
        this.moodState = moodState;
    }

    public void setWasActiveState(boolean wasActiveState) {
        this.wasActiveState = wasActiveState;
    }

    public void setAteState(boolean ateState) {
        this.ateState = ateState;
    }

    public void setSpokeState(boolean spokeState) {
        this.spokeState = spokeState;
    }

    public void setAccepted(boolean accepted) {
        this.accepted = accepted;
    }

    public String toCSVLine(){

        String csvString =
                personID +
                        "," + dayNum + ":" + hour + ":" + minute +
                        "," + kYouActivityType.toString() +
                        "," + metaData +
                        "," + moodState.toString() +
                        "," + wasActiveState +
                        "," + ateState +
                        "," + spokeState +
                        "," + accepted + "\n";

        return csvString;
    }

    @Override
    public String toString() {
        return "MLEvent{" +
                "personID=" + personID +
                ", timestamp (dd:hh:mm)= " + dayNum +
                ":" + hour +
                ":" + minute +
                ", kYouActivityType=" + kYouActivityType +
                ", metaData=" + metaData +
                ", moodState=" + moodState +
                ", wasActiveState=" + wasActiveState +
                ", ateState=" + ateState +
                ", spokeState=" + spokeState +
                ", accepted=" + accepted +
                '}';
    }
}
